export const CREATE_CUSTOMER = 'CREATE_CUSTOMER_CHAIN';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER_CHAIN';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER_CHAIN';
export const GET_CUSTOMERS = 'GET_CUSTOMERS_CHAIN';
export const CUSTOMER_ERROR_HANDLER = 'CUSTOMER_ERROR_HANDLER_CHAIN';
