export const CREATE_ORDER = 'CREATE_ORDER_CHAIN';
export const DELETE_ORDER = 'DELETE_ORDER_CHAIN';
export const GET_ORDERS = 'GET_ORDERS_CHAIN';
export const UPDATE_ORDER = 'UPDATE_ORDER_CHAIN';
export const ORDER_ERROR_HANDLER = 'ORDER_ERROR_HANDLER_CHAIN';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS_CHAIN';