export const CREATE_USER = 'CREATE_USER_CHAIN';
export const DELETE_USER = 'DELETE_USER_CHAIN';
export const GET_USERS = 'GET_USERS_CHAIN';
export const UPDATE_USER = 'UPDATE_USER_CHAIN';
export const USER_ERROR_HANDLER = 'USER_ERROR_HANDLER';